### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Sarcasm** [Sarcasm/irony-mode#132]
Collection of tasks/things to fix for irony-mode to work on Windows.
- [x] Disable buffer undo list. Hide the buffer as well, see https://www.gnu.org/software/emacs/manual/html_node/elisp/Maintaining-Undo.html and http://www.gnu.org/software/emacs/manual/html_node/elisp/Buffer-Names.html
- [x] Improve CMake build and document assumptions, such as whether or not libclang.dll should be in the PATH (see  http://stackoverflow.com/a/230425/951426). Whether or not libclang.imp has to be dealt with in a special way.
- [x] Check whether or not we have to define `_CINDEX_LIB_` or similar when building with shared/static libclang, see c:/Program Files (x86)/LLVM/include/clang-c/Platform.h for details.
- [x] use `start-process` instead of `start-process-shell-command`, see https://github.com/Sarcasm/irony-mode/issues/131#issuecomment-58940244
- [x] `irony--server-command` shouldn't use the Unix convention of `$$` to make the log file unique, see [irony.el@17d7f39#L550](https://github.com/Sarcasm/irony-mode/blob/17d7f39012768b72966f60133325c175b97671d9/irony.el#L550).
- [x] remove call of `std::stoi` apparently not supported on some flavor of MinGW (see #104).
- [x] document how to submit the LLVM install path on Windows, or add it to FindLibclang.cmake (see https://github.com/Sarcasm/irony-mode/issues/104#issuecomment-46287894).
- [x] Make sure to understand why Emacs seems to freeze (#104). **edit: seems to be fixed in Emacs 24.4 (see https://github.com/Sarcasm/irony-mode/issues/131#issuecomment-59667329)**
- [x] Fix CheckLibClangBuiltinHeadersDir.cmake for Windows.
- [x] Find how to deal with `w32-pipe-read-delay`. Should we ask the user to set it? Should we set it temporarily?
- [x] Check whether or not to set `process-adaptive-read-buffering`. **edit: setting it to nil gives better times, see https://github.com/Sarcasm/irony-mode/issues/131#issuecomment-60008803**
- [x] Edit the Windows Wiki page to take the changes into account.
- [x] make sure to flush at the end of a request
- [x] fix issues with iterator debugging enabled when compiling with native Windows. This code https://github.com/Sarcasm/irony-mode/blob/1d890abf09387e75846ede29031decc8baafc826/server/src/support/CommandLineParser.cpp#L20 makes windows debugging build crash even if we know what we are doing.
- [x] add an interactive command to kill the irony-server process(es). Use this function be rebuilding/reinstalling the server and a command, since on Windows it's not possible to touch a running binary apparently.
- [x] make sure irony-server executable is found automatically
