### ISSUE TITLE
Introduce version

### ISSUE THREAD

**Issue by Sarcasm** [Sarcasm/irony-mode#18]
# Tasks
- [x] add version `irony-mode-version` variable (see below)
- [x] create corresponding tag in git and create a tag for the develop branch
- [x] add version in `irony.el` comment (see below) and other files
- [x] document everything, "normal" workflow to start quickly
- [x] update MELPA/el-get recipe
## `irony-mode-version` variable

When the first "stable" version will appear, do not forget to start offering a version variable.

``` lisp
(defvar irony-mode-version "0.1"
"<irony-mode version variable blabla>")
```

Use a format like:

```
MAJOR.MINOR[.SUBMINOR-IF-IT-MAKES-SENSE?].
```

Look at the function `version-to-list` and document it, this idea come from a discussion in the following pull request: https://github.com/auto-complete/auto-complete/pull/161#issuecomment-8598159
## Version comment

In addition to the variable, add the following information to the main file, after `Author`:

```
;; URL: https://github.com/Sarcasm/irony-mode
;; Version: 0.1
```
