### ISSUE TITLE
Merge completion plugin into one

### ISSUE THREAD

**Issue by Sarcasm** [Sarcasm/irony-mode#21]
Since the last version of my `auto-complete` fork introduced a version that can be checked, the plugins irony-ac and irony-ac-simple can be merged into one (and limit unnecessary duplicated code). Hopefully, if one day `auto-complete` makes my fork obsolete we will be able to add support to the new version quite easily.
# Tasks
- [x] merge `irony-ac` and `irony-ac-simple` (see 8415a15)
- [x] merge `irony-ac-header-comp` so header completion will be seamlessly integrated as part of the completion plugin (see related issue #16)
- [x] fix related issue header completion issue #9
- [x] update documentation/README (see 516d204)
