### ISSUE TITLE
Create an easily installable package

### ISSUE THREAD

**Issue by Sarcasm** [Sarcasm/irony-mode#36]
# Tasks
- [x] Make it work with `el-get`, this is a tool that I know almost for sure can do a "1 click install". The standard package system of Emacs on the other doesn't integrate the idea of compilation steps for example I think.
- [x] Check Emacs byte-compilation, it improves performance significantly while parsing an entry of a compilation-db. http://www.gnu.org/software/emacs/manual/html_node/elisp/Byte-Compilation.html using `(byte-compile 'irony-split-command-line)` and `(byte-compile 'irony-split-command-line)` divide the time by ~2.
- [ ] Play with CMake to retrieve Clang if not on the system. Some binaries of Clang can be found here: http://llvm.org/releases/download.html
